/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SignRouteImport } from './routes/sign'
import { Route as AuthedAppRouteImport } from './routes/_authed/_app'
import { Route as AuthedAdminRouteRouteImport } from './routes/_authed/admin/route'
import { Route as AuthedSettingsRouteRouteImport } from './routes/_authed/settings/route'
import { Route as AuthedAppIndexRouteImport } from './routes/_authed/_app/index'
import { Route as AuthedAppBotRouteImport } from './routes/_authed/_app/bot'
import { Route as AuthedAppSkillsRouteImport } from './routes/_authed/_app/skills'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed/admin/index'
import { Route as AuthedAdminArtifactsRouteImport } from './routes/_authed/admin/artifacts'
import { Route as AuthedAdminAuditRouteImport } from './routes/_authed/admin/audit'
import { Route as AuthedAdminBoundariesRouteImport } from './routes/_authed/admin/boundaries'
import { Route as AuthedAdminComputersRouteImport } from './routes/_authed/admin/computers'
import { Route as AuthedAdminConnectionsRouteImport } from './routes/_authed/admin/connections'
import { Route as AuthedAdminCredentialsRouteImport } from './routes/_authed/admin/credentials'
import { Route as AuthedAdminIdentityProvidersRouteImport } from './routes/_authed/admin/identity-providers'
import { Route as AuthedAdminModelsRouteImport } from './routes/_authed/admin/models'
import { Route as AuthedAdminPeopleRouteImport } from './routes/_authed/admin/people'
import { Route as AuthedAdminPlaygroundRouteImport } from './routes/_authed/admin/playground'
import { Route as AuthedAdminSkillsRouteImport } from './routes/_authed/admin/skills'
import { Route as AuthedAdminTriggersRouteImport } from './routes/_authed/admin/triggers'
import { Route as AuthedAdminUsageRouteImport } from './routes/_authed/admin/usage'
import { Route as AuthedSettingsIndexRouteImport } from './routes/_authed/settings/index'
import { Route as AuthedAppAgentsIndexRouteImport } from './routes/_authed/_app/agents/index'
import { Route as AuthedAppChannelChannelIdRouteImport } from './routes/_authed/_app/channel/$channelId'
import { Route as AuthedAppChannelNewRouteImport } from './routes/_authed/_app/channel/new'
import { Route as AuthedAdminComponentsIndexRouteImport } from './routes/_authed/admin/components/index'
import { Route as AuthedAdminComponentsNameRouteImport } from './routes/_authed/admin/components/$name'
import { Route as AuthedAdminPluginsIndexRouteImport } from './routes/_authed/admin/plugins/index'
import { Route as AuthedAdminPluginsKeyRouteImport } from './routes/_authed/admin/plugins/$key'
import { Route as AuthedSettingsComponentsGalleryIndexRouteImport } from './routes/_authed/settings/components-gallery/index'
import { Route as AuthedSettingsComponentsGalleryNameRouteImport } from './routes/_authed/settings/components-gallery/$name'
import { Route as AuthedSettingsConnectedAccountsIndexRouteImport } from './routes/_authed/settings/connected-accounts/index'
import { Route as AuthedSettingsConnectedAccountsKeyRouteImport } from './routes/_authed/settings/connected-accounts/$key'
import { Route as AuthedAdminPluginsKeyToolsToolRouteImport } from './routes/_authed/admin/plugins/$key_.tools.$tool'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SignRoute = SignRouteImport.update({
  id: '/sign',
  path: '/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAppRoute = AuthedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRouteRoute = AuthedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRouteRoute = AuthedSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppIndexRoute = AuthedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppBotRoute = AuthedAppBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppSkillsRoute = AuthedAppSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminArtifactsRoute = AuthedAdminArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminAuditRoute = AuthedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminBoundariesRoute = AuthedAdminBoundariesRouteImport.update({
  id: '/boundaries',
  path: '/boundaries',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminComputersRoute = AuthedAdminComputersRouteImport.update({
  id: '/computers',
  path: '/computers',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminConnectionsRoute = AuthedAdminConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminCredentialsRoute = AuthedAdminCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminIdentityProvidersRoute =
  AuthedAdminIdentityProvidersRouteImport.update({
    id: '/identity-providers',
    path: '/identity-providers',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminModelsRoute = AuthedAdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPeopleRoute = AuthedAdminPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPlaygroundRoute = AuthedAdminPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminSkillsRoute = AuthedAdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminTriggersRoute = AuthedAdminTriggersRouteImport.update({
  id: '/triggers',
  path: '/triggers',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminUsageRoute = AuthedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedSettingsIndexRoute = AuthedSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSettingsRouteRoute,
} as any)
const AuthedAppAgentsIndexRoute = AuthedAppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAppChannelChannelIdRoute =
  AuthedAppChannelChannelIdRouteImport.update({
    id: '/channel/$channelId',
    path: '/channel/$channelId',
    getParentRoute: () => AuthedAppRoute,
  } as any)
const AuthedAppChannelNewRoute = AuthedAppChannelNewRouteImport.update({
  id: '/channel/new',
  path: '/channel/new',
  getParentRoute: () => AuthedAppRoute,
} as any)
const AuthedAdminComponentsIndexRoute =
  AuthedAdminComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminComponentsNameRoute =
  AuthedAdminComponentsNameRouteImport.update({
    id: '/components/$name',
    path: '/components/$name',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)
const AuthedAdminPluginsIndexRoute = AuthedAdminPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedAdminPluginsKeyRoute = AuthedAdminPluginsKeyRouteImport.update({
  id: '/plugins/$key',
  path: '/plugins/$key',
  getParentRoute: () => AuthedAdminRouteRoute,
} as any)
const AuthedSettingsComponentsGalleryIndexRoute =
  AuthedSettingsComponentsGalleryIndexRouteImport.update({
    id: '/components-gallery/',
    path: '/components-gallery/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsComponentsGalleryNameRoute =
  AuthedSettingsComponentsGalleryNameRouteImport.update({
    id: '/components-gallery/$name',
    path: '/components-gallery/$name',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsConnectedAccountsIndexRoute =
  AuthedSettingsConnectedAccountsIndexRouteImport.update({
    id: '/connected-accounts/',
    path: '/connected-accounts/',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedSettingsConnectedAccountsKeyRoute =
  AuthedSettingsConnectedAccountsKeyRouteImport.update({
    id: '/connected-accounts/$key',
    path: '/connected-accounts/$key',
    getParentRoute: () => AuthedSettingsRouteRoute,
  } as any)
const AuthedAdminPluginsKeyToolsToolRoute =
  AuthedAdminPluginsKeyToolsToolRouteImport.update({
    id: '/plugins/$key_/tools/$tool',
    path: '/plugins/$key/tools/$tool',
    getParentRoute: () => AuthedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/admin': typeof AuthedAdminRouteRouteWithChildren
  '/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/bot': typeof AuthedAppBotRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/admin/artifacts': typeof AuthedAdminArtifactsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/connections': typeof AuthedAdminConnectionsRoute
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/admin/models': typeof AuthedAdminModelsRoute
  '/admin/people': typeof AuthedAdminPeopleRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/skills': typeof AuthedAdminSkillsRoute
  '/admin/triggers': typeof AuthedAdminTriggersRoute
  '/admin/usage': typeof AuthedAdminUsageRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/settings/': typeof AuthedSettingsIndexRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/admin/plugins/$key': typeof AuthedAdminPluginsKeyRoute
  '/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/settings/connected-accounts/$key': typeof AuthedSettingsConnectedAccountsKeyRoute
  '/agents/': typeof AuthedAppAgentsIndexRoute
  '/admin/components/': typeof AuthedAdminComponentsIndexRoute
  '/admin/plugins/': typeof AuthedAdminPluginsIndexRoute
  '/settings/components-gallery/': typeof AuthedSettingsComponentsGalleryIndexRoute
  '/settings/connected-accounts/': typeof AuthedSettingsConnectedAccountsIndexRoute
  '/admin/plugins/$key/tools/$tool': typeof AuthedAdminPluginsKeyToolsToolRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedAppIndexRoute
  '/sign': typeof SignRoute
  '/bot': typeof AuthedAppBotRoute
  '/skills': typeof AuthedAppSkillsRoute
  '/admin/artifacts': typeof AuthedAdminArtifactsRoute
  '/admin/audit': typeof AuthedAdminAuditRoute
  '/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/admin/computers': typeof AuthedAdminComputersRoute
  '/admin/connections': typeof AuthedAdminConnectionsRoute
  '/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/admin/models': typeof AuthedAdminModelsRoute
  '/admin/people': typeof AuthedAdminPeopleRoute
  '/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/admin/skills': typeof AuthedAdminSkillsRoute
  '/admin/triggers': typeof AuthedAdminTriggersRoute
  '/admin/usage': typeof AuthedAdminUsageRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/settings': typeof AuthedSettingsIndexRoute
  '/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/channel/new': typeof AuthedAppChannelNewRoute
  '/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/admin/plugins/$key': typeof AuthedAdminPluginsKeyRoute
  '/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/settings/connected-accounts/$key': typeof AuthedSettingsConnectedAccountsKeyRoute
  '/agents': typeof AuthedAppAgentsIndexRoute
  '/admin/components': typeof AuthedAdminComponentsIndexRoute
  '/admin/plugins': typeof AuthedAdminPluginsIndexRoute
  '/settings/components-gallery': typeof AuthedSettingsComponentsGalleryIndexRoute
  '/settings/connected-accounts': typeof AuthedSettingsConnectedAccountsIndexRoute
  '/admin/plugins/$key/tools/$tool': typeof AuthedAdminPluginsKeyToolsToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/sign': typeof SignRoute
  '/_authed/admin': typeof AuthedAdminRouteRouteWithChildren
  '/_authed/settings': typeof AuthedSettingsRouteRouteWithChildren
  '/_authed/_app': typeof AuthedAppRouteWithChildren
  '/_authed/_app/bot': typeof AuthedAppBotRoute
  '/_authed/_app/skills': typeof AuthedAppSkillsRoute
  '/_authed/admin/artifacts': typeof AuthedAdminArtifactsRoute
  '/_authed/admin/audit': typeof AuthedAdminAuditRoute
  '/_authed/admin/boundaries': typeof AuthedAdminBoundariesRoute
  '/_authed/admin/computers': typeof AuthedAdminComputersRoute
  '/_authed/admin/connections': typeof AuthedAdminConnectionsRoute
  '/_authed/admin/credentials': typeof AuthedAdminCredentialsRoute
  '/_authed/admin/identity-providers': typeof AuthedAdminIdentityProvidersRoute
  '/_authed/admin/models': typeof AuthedAdminModelsRoute
  '/_authed/admin/people': typeof AuthedAdminPeopleRoute
  '/_authed/admin/playground': typeof AuthedAdminPlaygroundRoute
  '/_authed/admin/skills': typeof AuthedAdminSkillsRoute
  '/_authed/admin/triggers': typeof AuthedAdminTriggersRoute
  '/_authed/admin/usage': typeof AuthedAdminUsageRoute
  '/_authed/_app/': typeof AuthedAppIndexRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/settings/': typeof AuthedSettingsIndexRoute
  '/_authed/_app/channel/$channelId': typeof AuthedAppChannelChannelIdRoute
  '/_authed/_app/channel/new': typeof AuthedAppChannelNewRoute
  '/_authed/admin/components/$name': typeof AuthedAdminComponentsNameRoute
  '/_authed/admin/plugins/$key': typeof AuthedAdminPluginsKeyRoute
  '/_authed/settings/components-gallery/$name': typeof AuthedSettingsComponentsGalleryNameRoute
  '/_authed/settings/connected-accounts/$key': typeof AuthedSettingsConnectedAccountsKeyRoute
  '/_authed/_app/agents/': typeof AuthedAppAgentsIndexRoute
  '/_authed/admin/components/': typeof AuthedAdminComponentsIndexRoute
  '/_authed/admin/plugins/': typeof AuthedAdminPluginsIndexRoute
  '/_authed/settings/components-gallery/': typeof AuthedSettingsComponentsGalleryIndexRoute
  '/_authed/settings/connected-accounts/': typeof AuthedSettingsConnectedAccountsIndexRoute
  '/_authed/admin/plugins/$key_/tools/$tool': typeof AuthedAdminPluginsKeyToolsToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign'
    | '/admin'
    | '/settings'
    | '/bot'
    | '/skills'
    | '/admin/artifacts'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/computers'
    | '/admin/connections'
    | '/admin/credentials'
    | '/admin/identity-providers'
    | '/admin/models'
    | '/admin/people'
    | '/admin/playground'
    | '/admin/skills'
    | '/admin/triggers'
    | '/admin/usage'
    | '/admin/'
    | '/settings/'
    | '/channel/$channelId'
    | '/channel/new'
    | '/admin/components/$name'
    | '/admin/plugins/$key'
    | '/settings/components-gallery/$name'
    | '/settings/connected-accounts/$key'
    | '/agents/'
    | '/admin/components/'
    | '/admin/plugins/'
    | '/settings/components-gallery/'
    | '/settings/connected-accounts/'
    | '/admin/plugins/$key/tools/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign'
    | '/bot'
    | '/skills'
    | '/admin/artifacts'
    | '/admin/audit'
    | '/admin/boundaries'
    | '/admin/computers'
    | '/admin/connections'
    | '/admin/credentials'
    | '/admin/identity-providers'
    | '/admin/models'
    | '/admin/people'
    | '/admin/playground'
    | '/admin/skills'
    | '/admin/triggers'
    | '/admin/usage'
    | '/admin'
    | '/settings'
    | '/channel/$channelId'
    | '/channel/new'
    | '/admin/components/$name'
    | '/admin/plugins/$key'
    | '/settings/components-gallery/$name'
    | '/settings/connected-accounts/$key'
    | '/agents'
    | '/admin/components'
    | '/admin/plugins'
    | '/settings/components-gallery'
    | '/settings/connected-accounts'
    | '/admin/plugins/$key/tools/$tool'
  id:
    | '__root__'
    | '/_authed'
    | '/sign'
    | '/_authed/admin'
    | '/_authed/settings'
    | '/_authed/_app'
    | '/_authed/_app/bot'
    | '/_authed/_app/skills'
    | '/_authed/admin/artifacts'
    | '/_authed/admin/audit'
    | '/_authed/admin/boundaries'
    | '/_authed/admin/computers'
    | '/_authed/admin/connections'
    | '/_authed/admin/credentials'
    | '/_authed/admin/identity-providers'
    | '/_authed/admin/models'
    | '/_authed/admin/people'
    | '/_authed/admin/playground'
    | '/_authed/admin/skills'
    | '/_authed/admin/triggers'
    | '/_authed/admin/usage'
    | '/_authed/_app/'
    | '/_authed/admin/'
    | '/_authed/settings/'
    | '/_authed/_app/channel/$channelId'
    | '/_authed/_app/channel/new'
    | '/_authed/admin/components/$name'
    | '/_authed/admin/plugins/$key'
    | '/_authed/settings/components-gallery/$name'
    | '/_authed/settings/connected-accounts/$key'
    | '/_authed/_app/agents/'
    | '/_authed/admin/components/'
    | '/_authed/admin/plugins/'
    | '/_authed/settings/components-gallery/'
    | '/_authed/settings/connected-accounts/'
    | '/_authed/admin/plugins/$key_/tools/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  SignRoute: typeof SignRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign': {
      id: '/sign'
      path: '/sign'
      fullPath: '/sign'
      preLoaderRoute: typeof SignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/_app': {
      id: '/_authed/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_app/': {
      id: '/_authed/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedAppIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/bot': {
      id: '/_authed/_app/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof AuthedAppBotRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/skills': {
      id: '/_authed/_app/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof AuthedAppSkillsRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/artifacts': {
      id: '/_authed/admin/artifacts'
      path: '/artifacts'
      fullPath: '/admin/artifacts'
      preLoaderRoute: typeof AuthedAdminArtifactsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/audit': {
      id: '/_authed/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthedAdminAuditRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/boundaries': {
      id: '/_authed/admin/boundaries'
      path: '/boundaries'
      fullPath: '/admin/boundaries'
      preLoaderRoute: typeof AuthedAdminBoundariesRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/computers': {
      id: '/_authed/admin/computers'
      path: '/computers'
      fullPath: '/admin/computers'
      preLoaderRoute: typeof AuthedAdminComputersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/connections': {
      id: '/_authed/admin/connections'
      path: '/connections'
      fullPath: '/admin/connections'
      preLoaderRoute: typeof AuthedAdminConnectionsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/credentials': {
      id: '/_authed/admin/credentials'
      path: '/credentials'
      fullPath: '/admin/credentials'
      preLoaderRoute: typeof AuthedAdminCredentialsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/identity-providers': {
      id: '/_authed/admin/identity-providers'
      path: '/identity-providers'
      fullPath: '/admin/identity-providers'
      preLoaderRoute: typeof AuthedAdminIdentityProvidersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/models': {
      id: '/_authed/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AuthedAdminModelsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/people': {
      id: '/_authed/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthedAdminPeopleRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/playground': {
      id: '/_authed/admin/playground'
      path: '/playground'
      fullPath: '/admin/playground'
      preLoaderRoute: typeof AuthedAdminPlaygroundRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/skills': {
      id: '/_authed/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthedAdminSkillsRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/triggers': {
      id: '/_authed/admin/triggers'
      path: '/triggers'
      fullPath: '/admin/triggers'
      preLoaderRoute: typeof AuthedAdminTriggersRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/usage': {
      id: '/_authed/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthedAdminUsageRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/settings/': {
      id: '/_authed/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthedSettingsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/_app/agents/': {
      id: '/_authed/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthedAppAgentsIndexRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/$channelId': {
      id: '/_authed/_app/channel/$channelId'
      path: '/channel/$channelId'
      fullPath: '/channel/$channelId'
      preLoaderRoute: typeof AuthedAppChannelChannelIdRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/_app/channel/new': {
      id: '/_authed/_app/channel/new'
      path: '/channel/new'
      fullPath: '/channel/new'
      preLoaderRoute: typeof AuthedAppChannelNewRouteImport
      parentRoute: typeof AuthedAppRoute
    }
    '/_authed/admin/components/': {
      id: '/_authed/admin/components/'
      path: '/components'
      fullPath: '/admin/components/'
      preLoaderRoute: typeof AuthedAdminComponentsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/components/$name': {
      id: '/_authed/admin/components/$name'
      path: '/components/$name'
      fullPath: '/admin/components/$name'
      preLoaderRoute: typeof AuthedAdminComponentsNameRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins/': {
      id: '/_authed/admin/plugins/'
      path: '/plugins'
      fullPath: '/admin/plugins/'
      preLoaderRoute: typeof AuthedAdminPluginsIndexRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/admin/plugins/$key': {
      id: '/_authed/admin/plugins/$key'
      path: '/plugins/$key'
      fullPath: '/admin/plugins/$key'
      preLoaderRoute: typeof AuthedAdminPluginsKeyRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
    '/_authed/settings/components-gallery/': {
      id: '/_authed/settings/components-gallery/'
      path: '/components-gallery'
      fullPath: '/settings/components-gallery/'
      preLoaderRoute: typeof AuthedSettingsComponentsGalleryIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/components-gallery/$name': {
      id: '/_authed/settings/components-gallery/$name'
      path: '/components-gallery/$name'
      fullPath: '/settings/components-gallery/$name'
      preLoaderRoute: typeof AuthedSettingsComponentsGalleryNameRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/connected-accounts/': {
      id: '/_authed/settings/connected-accounts/'
      path: '/connected-accounts'
      fullPath: '/settings/connected-accounts/'
      preLoaderRoute: typeof AuthedSettingsConnectedAccountsIndexRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/settings/connected-accounts/$key': {
      id: '/_authed/settings/connected-accounts/$key'
      path: '/connected-accounts/$key'
      fullPath: '/settings/connected-accounts/$key'
      preLoaderRoute: typeof AuthedSettingsConnectedAccountsKeyRouteImport
      parentRoute: typeof AuthedSettingsRouteRoute
    }
    '/_authed/admin/plugins/$key_/tools/$tool': {
      id: '/_authed/admin/plugins/$key_/tools/$tool'
      path: '/plugins/$key/tools/$tool'
      fullPath: '/admin/plugins/$key/tools/$tool'
      preLoaderRoute: typeof AuthedAdminPluginsKeyToolsToolRouteImport
      parentRoute: typeof AuthedAdminRouteRoute
    }
  }
}

interface AuthedAdminRouteRouteChildren {
  AuthedAdminArtifactsRoute: typeof AuthedAdminArtifactsRoute
  AuthedAdminAuditRoute: typeof AuthedAdminAuditRoute
  AuthedAdminBoundariesRoute: typeof AuthedAdminBoundariesRoute
  AuthedAdminComputersRoute: typeof AuthedAdminComputersRoute
  AuthedAdminConnectionsRoute: typeof AuthedAdminConnectionsRoute
  AuthedAdminCredentialsRoute: typeof AuthedAdminCredentialsRoute
  AuthedAdminIdentityProvidersRoute: typeof AuthedAdminIdentityProvidersRoute
  AuthedAdminModelsRoute: typeof AuthedAdminModelsRoute
  AuthedAdminPeopleRoute: typeof AuthedAdminPeopleRoute
  AuthedAdminPlaygroundRoute: typeof AuthedAdminPlaygroundRoute
  AuthedAdminSkillsRoute: typeof AuthedAdminSkillsRoute
  AuthedAdminTriggersRoute: typeof AuthedAdminTriggersRoute
  AuthedAdminUsageRoute: typeof AuthedAdminUsageRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
  AuthedAdminComponentsNameRoute: typeof AuthedAdminComponentsNameRoute
  AuthedAdminPluginsKeyRoute: typeof AuthedAdminPluginsKeyRoute
  AuthedAdminComponentsIndexRoute: typeof AuthedAdminComponentsIndexRoute
  AuthedAdminPluginsIndexRoute: typeof AuthedAdminPluginsIndexRoute
  AuthedAdminPluginsKeyToolsToolRoute: typeof AuthedAdminPluginsKeyToolsToolRoute
}

const AuthedAdminRouteRouteChildren: AuthedAdminRouteRouteChildren = {
  AuthedAdminArtifactsRoute: AuthedAdminArtifactsRoute,
  AuthedAdminAuditRoute: AuthedAdminAuditRoute,
  AuthedAdminBoundariesRoute: AuthedAdminBoundariesRoute,
  AuthedAdminComputersRoute: AuthedAdminComputersRoute,
  AuthedAdminConnectionsRoute: AuthedAdminConnectionsRoute,
  AuthedAdminCredentialsRoute: AuthedAdminCredentialsRoute,
  AuthedAdminIdentityProvidersRoute: AuthedAdminIdentityProvidersRoute,
  AuthedAdminModelsRoute: AuthedAdminModelsRoute,
  AuthedAdminPeopleRoute: AuthedAdminPeopleRoute,
  AuthedAdminPlaygroundRoute: AuthedAdminPlaygroundRoute,
  AuthedAdminSkillsRoute: AuthedAdminSkillsRoute,
  AuthedAdminTriggersRoute: AuthedAdminTriggersRoute,
  AuthedAdminUsageRoute: AuthedAdminUsageRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
  AuthedAdminComponentsNameRoute: AuthedAdminComponentsNameRoute,
  AuthedAdminPluginsKeyRoute: AuthedAdminPluginsKeyRoute,
  AuthedAdminComponentsIndexRoute: AuthedAdminComponentsIndexRoute,
  AuthedAdminPluginsIndexRoute: AuthedAdminPluginsIndexRoute,
  AuthedAdminPluginsKeyToolsToolRoute: AuthedAdminPluginsKeyToolsToolRoute,
}

const AuthedAdminRouteRouteWithChildren =
  AuthedAdminRouteRoute._addFileChildren(AuthedAdminRouteRouteChildren)

interface AuthedSettingsRouteRouteChildren {
  AuthedSettingsIndexRoute: typeof AuthedSettingsIndexRoute
  AuthedSettingsComponentsGalleryNameRoute: typeof AuthedSettingsComponentsGalleryNameRoute
  AuthedSettingsConnectedAccountsKeyRoute: typeof AuthedSettingsConnectedAccountsKeyRoute
  AuthedSettingsComponentsGalleryIndexRoute: typeof AuthedSettingsComponentsGalleryIndexRoute
  AuthedSettingsConnectedAccountsIndexRoute: typeof AuthedSettingsConnectedAccountsIndexRoute
}

const AuthedSettingsRouteRouteChildren: AuthedSettingsRouteRouteChildren = {
  AuthedSettingsIndexRoute: AuthedSettingsIndexRoute,
  AuthedSettingsComponentsGalleryNameRoute:
    AuthedSettingsComponentsGalleryNameRoute,
  AuthedSettingsConnectedAccountsKeyRoute:
    AuthedSettingsConnectedAccountsKeyRoute,
  AuthedSettingsComponentsGalleryIndexRoute:
    AuthedSettingsComponentsGalleryIndexRoute,
  AuthedSettingsConnectedAccountsIndexRoute:
    AuthedSettingsConnectedAccountsIndexRoute,
}

const AuthedSettingsRouteRouteWithChildren =
  AuthedSettingsRouteRoute._addFileChildren(AuthedSettingsRouteRouteChildren)

interface AuthedAppRouteChildren {
  AuthedAppBotRoute: typeof AuthedAppBotRoute
  AuthedAppSkillsRoute: typeof AuthedAppSkillsRoute
  AuthedAppIndexRoute: typeof AuthedAppIndexRoute
  AuthedAppChannelChannelIdRoute: typeof AuthedAppChannelChannelIdRoute
  AuthedAppChannelNewRoute: typeof AuthedAppChannelNewRoute
  AuthedAppAgentsIndexRoute: typeof AuthedAppAgentsIndexRoute
}

const AuthedAppRouteChildren: AuthedAppRouteChildren = {
  AuthedAppBotRoute: AuthedAppBotRoute,
  AuthedAppSkillsRoute: AuthedAppSkillsRoute,
  AuthedAppIndexRoute: AuthedAppIndexRoute,
  AuthedAppChannelChannelIdRoute: AuthedAppChannelChannelIdRoute,
  AuthedAppChannelNewRoute: AuthedAppChannelNewRoute,
  AuthedAppAgentsIndexRoute: AuthedAppAgentsIndexRoute,
}

const AuthedAppRouteWithChildren = AuthedAppRoute._addFileChildren(
  AuthedAppRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRouteRoute: typeof AuthedAdminRouteRouteWithChildren
  AuthedSettingsRouteRoute: typeof AuthedSettingsRouteRouteWithChildren
  AuthedAppRoute: typeof AuthedAppRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRouteRoute: AuthedAdminRouteRouteWithChildren,
  AuthedSettingsRouteRoute: AuthedSettingsRouteRouteWithChildren,
  AuthedAppRoute: AuthedAppRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  SignRoute: SignRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
